qat16: depend on openssl10
Fixes error:

| Creating shared library cpa_sample_code_s.so
| x86_64-poky-linux-gcc -m64 -march=nehalem -mtune=generic -mfpmath=sse -msse4.2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/poky/build/tmp/work/intel_corei7_64-poky-linux/qat16/2.6.0-65-r0/recipe-sysroot -Wl,--hash-style=gnu -nostartfiles -nodefaultlibs -shared -Wl,-soname,cpa_sample_code_s.so -o cpa_sample_code_s.so -lc cpa_sample_code_utils.o cpa_sample_code_framework.o cpa_sample_code_main.o cpa_sample_code_crypto_utils.o cpa_sample_code_sym_perf.o cpa_sample_code_sym_perf_dp.o cpa_sample_code_rsa_perf.o cpa_sample_code_dsa_perf.o cpa_sample_code_ecdsa_perf.o cpa_sample_code_dh_perf.o cpa_sample_code_nrbg_perf.o cpa_sample_code_dc_utils.o cpa_sample_code_dc_dp.o cpa_sample_code_dc_2k.o cpa_sample_code_dc_stateful.o cpa_sample_code_zlib.o cpa_sample_code_ike_rsa_perf.o qae_mem_utils.o /poky/build/tmp/work/intel_corei7_64-poky-linux/qat16/2.6.0-65-r0/image/libicp_qa_al_s.so -L/Lib -lpthread -lcrypto -lrt
| Creating executable cpa_sample_code
| /poky/build/tmp/work/intel_corei7_64-poky-linux/qat16/2.6.0-65-r0/recipe-sysroot-native/usr/bin/x86_64-poky-linux/../../libexec/x86_64-poky-linux/gcc/x86_64-poky-linux/8.2.0/ld: /home/anmitta2/work/poky/build/tmp/work/intel_corei7_64-poky-linux/qat16/2.6.0-65-r0/image/libicp_qa_al_s.so: undefined reference to `SHA_Init'
| collect2: error: ld returned 1 exit status
| /poky/build/tmp/work/intel_corei7_64-poky-linux/qat16/2.6.0-65-r0/QAT1.6/quickassist/build_system/build_files/OS/linux_common_user_space_rules.mk:88: recipe for target 'cpa_sample_code' failed
| make[1]: *** [cpa_sample_code] Error 1
| make[1]: Leaving directory '/poky/build/tmp/work/intel_corei7_64-poky-linux/qat16/2.6.0-65-r0/QAT1.6/quickassist/lookaside/access_layer/src/sample_code/performance'
| Makefile:158: recipe for target 'perf_user' failed

Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>