qat: make do_fetch depend on kernel do_shared_workdir
If the recipe qat17 was built, and kernel was re-configure(i.e set
CONFIG_BACKTRACE_SELF_TEST=m), then rebuild the qat17 will trigger the
following error:

Exception: bb.process.ExecutionError: Execution of
tmp-glibc/work/intel_x86_64-wrs-linux/qat17/4.7.0-00006-r0/temp/run.do_switch_to_skcipher_api.42824'
failed with exit code 1:
patching file quickassist/qat/drivers/crypto/qat/qat_common/qat_algs.c
Reversed (or previously applied) patch detected! Assume -R? [n]
Apply anyway? [n]
Skipping patch.
32 out of 32 hunks ignored – saving rejects to file
quickassist/qat/drivers/crypto/qat/qat_common/qat_algs.c.rej
patching file quickassist/qat/drivers/crypto/qat/qat_common/qat_crypto.h
Reversed (or previously applied) patch detected! Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored – saving rejects to file
quickassist/qat/drivers/crypto/qat/qat_common/qat_crypto.h.rej
WARNING: exit code 1 from a shell command.

This is due to inappropriate dependency, the qat reciepe is re-applying
patch to the source code that do_patch has been executed. If
virtual/kernel is changed, qat should build from code fetching rather
than patching.

Signed-off-by: Yunguo Wei <yunguo.wei@windriver.com>
Signed-off-by: Jun Miao <jun.miao@windriver.com>
Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>